Set the paused argument in the gazebo empty_world.launch to False
project-march/simulation pull request #54
Opened 2020-05-01 13:50 UTC by JorisWeeda

## Description
In order to properly launch the moveit package the simulation time **must** be active otherwise the movegroups will not be initialized. If the movegroups are not initialised the init of the gait selection is not finished causing the state machine to be stuck waiting for the gait selection which will not be finished. Therefore the paused argument must be false. This will not cause any weird behavior of the simulation because the physics are loaded after the state machine is initialized. 

 
## Changes
* Set paused argument to false

2020-05-01 13:55 UTC, RutgerVanBeek submitted a review, later dismissed
I definitively approve this.

2020-05-04 07:31 UTC, Roelemans requested changes
Perhaps make a paused argument that is set to $(arg not balanced) in march.launch?

2020-05-04 07:56 UTC, JorisWeeda commented
>Perhaps make a paused argument that is set to $(arg not balanced) in march.launch?

We could add an argument but Rutger and I tested the normal simulation launch and the argument change did not degrade the functionalities of the simulation so maybe not necessary?

2020-05-04 08:05 UTC, Roelemans commented
The simulation is started paused to avoid the issue of feet flapping after startup (though you may have noticed that this does not always work). I am not sure how big that problem currently is. I do have a preference for starting it paused when possible, because I don't wanna look into the flappin feet again :upside_down_face:

2020-05-04 09:39 UTC, RutgerVanBeek commented
> The simulation is started paused to avoid the issue of feet flapping after startup (though you may have noticed that this does not always work). I am not sure how big that problem currently is. I do have a preference for starting it paused when possible, because I don't wanna look into the flappin feet again

The physics are only turned on when the state machine is finished initializing, right?
This just make the gazebo publish on `/clock`.

2020-05-04 10:29 UTC, Roelemans commented
That apparently did not work before though. I think because the controller also waits for the state machine to finish, which can lead to the physics starting before the controller. Please just only pause it when balance is false to make me happy :D

2020-05-05 08:20 UTC, RutgerVanBeek approved these changes

2020-05-05 09:28 UTC, Olavhaasie approved these changes

2020-05-05 09:40 UTC, Roelemans approved these changes

2020-05-05 09:41 UTC, merged