Change the controller to use the inertia estimator
project-march/simulation pull request #59
Opened 2020-07-16 10:20 UTC by Deakensbubbles

Closes PM-no name given

## Description

Changes the default controller in the simulation so that you can easily test the new shiny PR over at: https://github.com/project-march/hardware-interface/pull/278

## Changes

* Changed default controller to: inertia_trajectory_controller/JointTrajectoryController"

2020-07-17 09:33 UTC, Roelemans submitted a review, later dismissed

2020-07-20 10:45 UTC, Olavhaasie requested changes
Perhaps just add the inertia controller next to the effort controller so that you can choose in the launch file, which one you want?

2020-08-11 14:58 UTC, Olavhaasie approved these changes

2020-08-11 19:26 UTC, Roelemans approved these changes

2020-08-11 19:26 UTC, merged